### ISSUE TITLE
Optional description

### ISSUE THREAD

**Issue by diosby** [ronvanderheijden/vscode-phpdoc-generator#17]
I describe methods, because without descriptions those functions are not understanding, even when they have descriptions of parameters.

Comments must be generated with descriptions. 
Not all people use the description, therefore the it must be as option and default is enabled.

**Comment by ronvanderheijden** [comment]
Isn't this the same as `Use Names In Top`?

**Comment by diosby** [comment]
Yes, this is the same. I understood this later, when I saw the code.
Probably, the property name is not the best. 
I would use the following: useDescription, description, blockDescription. 

Usually, names of functions are not used in description, because we know those names.
