### ISSUE TITLE
Different formats of types and short types

### ISSUE THREAD

**Issue by diosby** [ronvanderheijden/vscode-phpdoc-generator#22]
I have the following code:
```php
    public function name(int $value): int
    {
        # code...
    }
```
I got the following comment:
```php
    /**
     * @param integer $value
     * 
     * @return int
     */
    public function name(int $value): int
    {
        # code...
    }
```
There are different formats of types: short and long. This should be controlled by the configuration and they should have the same format.

**Comment by ronvanderheijden** [comment]
I believe this should always be the short version, since we cannot use `name(integer $value): boolean`

**Comment by diosby** [comment]
Yes, we cannot use it, but types in documentation have the dependent from projects and teamleaders.
