### ISSUE TITLE
Does not generate comments to constants

### ISSUE THREAD

**Issue by diosby** [ronvanderheijden/vscode-phpdoc-generator#24]
```php
const VALUE = 'string';
```
=>
```php
/**
 * @var string
 */
const VALUE = 'string';
```

**Comment by ronvanderheijden** [comment]
This is incorrect when following PSR-12: https://www.php-fig.org/psr/psr-12/#43-properties-and-constants

> Visibility MUST be declared on all constants if your project PHP minimum version supports constant visibilities (PHP 7.1 or later).

**Comment by diosby** [comment]
My project use min version: php 7.0. 

But the following code has same problem:
```php
public const TEST = 'test';
```
Not everyone follows the PSR.
