### ISSUE TITLE
Generated @return comment is always void

### ISSUE THREAD

**Issue by t-hebert73** [ronvanderheijden/vscode-phpdoc-generator#5]
The @return comment for all functions is always void even when its explicitly an array or string etc.

**Comment by ronvanderheijden** [comment]
When using `public function getNumbers(): array`, a return value should be added. 

This plugin does not look for a return value in the code, I'm afraid.

**Comment by diosby** [comment]
```
/**
 * @return void
 */
public function name()
{}
```
Must be:
```
/**
 * Description for name.
 *
 * @return [type]
 */
public function name()
{}
```
or
```
/**
 * Description for name.
 */
public function name()
{}
```
**@return void** or **@return [type]** or **without @return** must be defined in as an option.
