### ISSUE TITLE
Detect function indentation

### ISSUE THREAD

**Issue by jcush** [ronvanderheijden/vscode-phpdoc-generator#6]
When using the keyboard shortcut on a function which is indented in the file, the resulting docblock does not detect this:

<img width="265" alt="Screenshot 2020-05-17 at 11 52 18" src="https://user-images.githubusercontent.com/10184859/82142539-f5560c80-9834-11ea-8370-c138a5ebf293.png">

It would be nice if this identation is detected and matched, using the user's current setting for spaces/tabs

**Comment by ronvanderheijden** [comment]
Is this issue fixed by https://github.com/ronvanderheijden/vscode-phpdoc-generator/issues/36?

**Comment by diosby** [comment]
@ronvanderheijden Yes, but it did not solve #12
